base:     dev-dev            # image to launch Docker with
repopath: github.com/Xe/dev  # repo path for mounting $CURDIR
golang:   true               # Go has a more opinionated package store
ssh:      true               # pass through ssh keys?
user:     xena               # user in the docker container
projname: dev                # project name

# Overlay is the dockerfile to overlay into this for `dev establish`
overlay: |
  FROM xena/base

  RUN echo "Hi mom!"
